"""Shared helpers for the docs-warden scripts.

Kept deliberately small: front matter parsing, config loading, and the two git
questions the audit needs. Anything used by exactly one script lives in that
script instead.
"""
import datetime as dt
import re
import subprocess
from pathlib import Path

import yaml

GENERATED_MARKER = "<!-- GENERATED by docs-warden - do not edit -->"

FRONT_MATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)

# Every document path in one place. The scripts import these rather than typing
# the literal, so a move like root -> docs/ is one edit and not six.
#
# README stays at root because GitHub renders it there and nowhere else. The
# manifest stays at root because that is where the scripts look for it before
# they know anything about the repository.
README = "README.md"
CONVENTIONS = "docs/CONVENTIONS.md"
DECISIONS = "docs/DECISIONS.md"
RUNLOG = "docs/RUNLOG.md"
GLOSSARY = "docs/GLOSSARY.md"
SECURITY = "docs/SECURITY.md"
DECISIONS_DIR = "docs/decisions"
RUNLOG_ARCHIVE_DIR = "docs/runlog"
MANIFEST = ".docs-warden.yml"

UNIVERSAL_FILES = [
    README,
    CONVENTIONS,
    DECISIONS,
    RUNLOG,
    GLOSSARY,
    SECURITY,
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/CODEOWNERS",
    MANIFEST,
    ".gitignore",
]


def parse_front_matter(text: str):
    """Return (front_matter_dict, body) for already-read text. Split out of
    read_front_matter so a blob out of git history is judged by exactly the
    same parse as the file on disk -- a second, regex-based definition of
    "what does this record's front matter say" is how the two drifted."""
    match = FRONT_MATTER_RE.match(text)
    if not match:
        return {}, text
    try:
        data = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        return {}, text[match.end():]
    if not isinstance(data, dict):
        return {}, text[match.end():]
    return data, text[match.end():]


def read_front_matter(path: Path):
    """Return (front_matter_dict, body). Missing or unparseable front matter
    gives an empty dict rather than raising -- the audit reports it as a
    finding, which is more useful than a traceback."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}, ""
    return parse_front_matter(text)


def review_date(value):
    """A review_by front-matter value as a date, or None if it is not one.

    datetime.datetime subclasses datetime.date, so a YAML timestamp --
    "review_by: 2026-01-01 09:00:00" is one -- satisfied an
    isinstance(value, dt.date) test and then raised TypeError the moment it was
    compared with today's date, taking the whole audit down. Narrowed to
    datetime first, and shared so the audit and the freshness report cannot
    drift into two answers for one question.
    """
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    try:
        return dt.date.fromisoformat(str(value))
    except ValueError:
        return None


def load_config(repo: Path):
    """Read .docs-warden.yml. Returns None when absent so callers can say so
    plainly instead of proceeding on invented defaults."""
    path = repo / MANIFEST
    if not path.is_file():
        return None
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (yaml.YAMLError, UnicodeDecodeError, OSError):
        # None means "cannot be read as a manifest", which the audit reports.
        # A traceback here would cost every check, not just this one.
        return None
    return data if isinstance(data, dict) else None


def parse_glossary(path: Path):
    """Return [(term, [rejected, ...])] from the glossary table."""
    entries = []
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            continue
        term, rejected = cells[0], cells[2]
        if not term or term.lower() == "term" or set(term) <= {"-", ":", " "}:
            continue
        if term.startswith("{{"):  # untouched template row
            continue
        rejects = [r.strip() for r in rejected.split(",")
                   if r.strip() and not r.strip().startswith("{{")]
        entries.append((term, rejects))
    return entries


def adr_files(repo: Path):
    """Decision record files, sorted by id."""
    decisions = repo / DECISIONS_DIR
    if not decisions.is_dir():
        return []
    return sorted(p for p in decisions.glob("DEC-*.md") if p.is_file())


def load_adrs(repo: Path):
    """Every decision record as a dict, with superseded_by derived from the
    other records rather than stored -- that is what keeps accepted files
    immutable."""
    records = []
    for path in adr_files(repo):
        front, _ = read_front_matter(path)
        # Fall back to the filename prefix (DEC-0007-slug -> DEC-0007) so a
        # record with broken front matter still appears in the index instead of
        # vanishing from it.
        fallback_id = "-".join(path.stem.split("-")[:2])
        records.append(
            {
                "path": path,
                "id": str(front.get("id") or fallback_id),
                "title": front.get("title", ""),
                "status": front.get("status", ""),
                "date": str(front.get("date", "")),
                "supersedes": front.get("supersedes") or [],
                "superseded_by": [],
            }
        )
    by_id = {r["id"]: r for r in records}
    for record in records:
        for old in record["supersedes"]:
            if old in by_id:
                by_id[old]["superseded_by"].append(record["id"])
    return records


def git(repo: Path, *args):
    """Run a git command, returning stdout or None if git cannot answer."""
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout


def is_git_repo(repo: Path) -> bool:
    return git(repo, "rev-parse", "--git-dir") is not None


def markdown_docs(repo: Path):
    """Every Markdown file that counts as documentation, skipping vendored and
    generated trees."""
    skip = {".git", "node_modules", "vendor", "dist", "build", ".venv"}
    for path in sorted(repo.rglob("*.md")):
        # Relative to the audited repo, never the absolute path: a repo checked
        # out under a directory called build/ or dist/ -- a CI workspace root,
        # commonly -- matched every one of its own documents against the skip
        # set and yielded nothing, which turned check_phi_secrets into a pass.
        if any(part in skip for part in path.relative_to(repo).parts):
            continue
        yield path


def strip_code(text: str) -> str:
    """Remove fenced blocks, inline code, and URLs. Prose checks run on what is
    left; flagging a term inside a code sample is noise."""
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    text = re.sub(r"`[^`\n]*`", "", text)
    # Stop at ")" as well as whitespace: a markdown link's closing paren
    # ("[text](https://url)") is not part of the URL, and \S alone swallows it.
    text = re.sub(r"https?://[^\s)]+", "", text)
    return text
