"""Shared helpers for the docs-warden scripts.

Kept deliberately small: front matter parsing, config loading, and the two git
questions the audit needs. Anything used by exactly one script lives in that
script instead.
"""
import datetime as dt
import re
import subprocess
from pathlib import Path

import yaml

GENERATED_MARKER = "<!-- GENERATED by docs-warden - do not edit -->"

FRONT_MATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)

# Every document path in one place. The scripts import these rather than typing
# the literal, so a move like root -> docs/ is one edit and not six.
#
# README stays at root because GitHub renders it there and nowhere else. The
# manifest stays at root because that is where the scripts look for it before
# they know anything about the repository.
README = "README.md"
CONVENTIONS = "docs/CONVENTIONS.md"
DECISIONS = "docs/DECISIONS.md"
RUNLOG = "docs/RUNLOG.md"
GLOSSARY = "docs/GLOSSARY.md"
SECURITY = "docs/SECURITY.md"
DOMAIN_MODEL = "docs/architecture/domain-model.md"
DECISIONS_DIR = "docs/decisions"
DECISIONS_ARCHIVE_DIR = "docs/decisions/archive"
RUNLOG_ARCHIVE_DIR = "docs/runlog"
MANIFEST = ".docs-warden.yml"

UNIVERSAL_FILES = [
    README,
    CONVENTIONS,
    DECISIONS,
    GLOSSARY,
    SECURITY,
    MANIFEST,
    ".gitignore",
]

# The review gate and the pull-request template are real controls, and every
# forge spells them differently. They sat in UNIVERSAL_FILES unconditionally,
# so a GitLab or Gitea repository failed required-files forever for something
# that is not a documentation defect -- the same argument that keeps LICENSE
# out of the universal set, decided the other way by accident.
#
# Absent from the manifest means github, because that is what every repository
# scaffolded so far assumes. Declaring it wrong is a failure, not a fallback.
FORGE_DEFAULT = "github"

FORGES = {
    "github": [
        ".github/PULL_REQUEST_TEMPLATE.md",
        ".github/CODEOWNERS",
    ],
    # GitLab's own documented locations: merge request templates are read from
    # .gitlab/merge_request_templates/, and CODEOWNERS from the repository
    # root, docs/ or .gitlab/ -- first one found wins, so any of the three
    # satisfies this.
    "gitlab": [
        ".gitlab/merge_request_templates/",
        ("CODEOWNERS", "docs/CODEOWNERS", ".gitlab/CODEOWNERS"),
    ],
    # A forge whose template convention this table does not know. Nothing is
    # required, and that is a real loss rather than a clean escape: the gate
    # that forces documentation into the same change still has to exist
    # somewhere, and now nothing checks that it does. Prefer naming the paths
    # with extra_files over selecting none.
    "none": [],
}


def read_doc(path: Path):
    """Text of a document, or None if the file cannot be read at all.

    errors="replace" survives undecodable bytes but not an unreadable file, so
    every walker that read a discovered path directly died on the first one it
    could not open -- a permission-restricted .md, a device node, a directory
    someone named x.md -- and took the whole scorecard with it, all the other
    checks included. One helper rather than a try/except per call site: the
    failure is identical at each, and a partial fix just moves the crash.

    None, never "": an empty document and an unreadable one are different
    findings, and the caller has to name the second one in its reason. Silently
    treating an unreadable file as empty prose is exactly the fake pass the
    skill's second non-negotiable forbids.
    """
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def parse_front_matter(text: str):
    """Return (front_matter_dict, body) for already-read text. Split out of
    read_front_matter so a blob out of git history is judged by exactly the
    same parse as the file on disk -- a second, regex-based definition of
    "what does this record's front matter say" is how the two drifted."""
    match = FRONT_MATTER_RE.match(text)
    if not match:
        return {}, text
    try:
        data = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        return {}, text[match.end():]
    if not isinstance(data, dict):
        return {}, text[match.end():]
    return data, text[match.end():]


def read_front_matter(path: Path):
    """Return (front_matter_dict, body). Missing or unparseable front matter
    gives an empty dict rather than raising -- the audit reports it as a
    finding, which is more useful than a traceback."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}, ""
    return parse_front_matter(text)


def review_date(value):
    """A review_by front-matter value as a date, or None if it is not one.

    datetime.datetime subclasses datetime.date, so a YAML timestamp --
    "review_by: 2026-01-01 09:00:00" is one -- satisfied an
    isinstance(value, dt.date) test and then raised TypeError the moment it was
    compared with today's date, taking the whole audit down. Narrowed to
    datetime first, and shared so the audit and the freshness report cannot
    drift into two answers for one question.
    """
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    try:
        return dt.date.fromisoformat(str(value))
    except ValueError:
        return None


def load_config(repo: Path):
    """Read .docs-warden.yml. Returns None when absent so callers can say so
    plainly instead of proceeding on invented defaults."""
    path = repo / MANIFEST
    if not path.is_file():
        return None
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (yaml.YAMLError, UnicodeDecodeError, OSError):
        # None means "cannot be read as a manifest", which the audit reports.
        # A traceback here would cost every check, not just this one.
        return None
    return data if isinstance(data, dict) else None


def parse_glossary(path: Path):
    """Return [(term, [rejected, ...])] from the glossary table."""
    entries = []
    text = read_doc(path)
    if text is None:
        return entries
    for line in text.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            continue
        term, rejected = cells[0], cells[2]
        if not term or term.lower() == "term" or set(term) <= {"-", ":", " "}:
            continue
        if term.startswith("{{"):  # untouched template row
            continue
        rejects = [r.strip() for r in rejected.split(",")
                   if r.strip() and not r.strip().startswith("{{")]
        entries.append((term, rejects))
    return entries


# The two tables domain_model.py renders, by their headings. The generator and
# the audit both read this, so they cannot drift into two answers for "what
# does a concept row look like".
DOMAIN_MODEL_SECTIONS = {
    "## Domain concepts": "domain",
    "## Technical concepts": "technical",
}


def parse_domain_model(path: Path):
    """Return [(concept, category)] from the generated domain model tables."""
    entries = []
    category = None
    text = read_doc(path)
    if text is None:
        return entries
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            category = DOMAIN_MODEL_SECTIONS.get(stripped)
            continue
        if category is None or not stripped.startswith("|"):
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        name = cells[0] if cells else ""
        if not name or name.lower() == "concept" or set(name) <= {"-", ":", " "}:
            continue
        entries.append((name, category))
    return entries


def long_lived_docs(repo):
    """Everything under docs/ that requires owner/review_by front matter. A stale
    architecture note is exactly as misleading as a stale CONVENTIONS, so this
    walks the whole tree rather than a fixed list of names."""
    docs = repo / "docs"
    if not docs.is_dir():
        return
    exempt = {(repo / RUNLOG).resolve()}
    archive = (repo / RUNLOG_ARCHIVE_DIR).resolve()
    decisions = (repo / DECISIONS_DIR).resolve()
    adr_archive = (repo / DECISIONS_ARCHIVE_DIR).resolve()
    for path in sorted(docs.rglob("*.md")):
        if path.name == "README.md":
            continue
        # The run log is append-only and has no owner in the review sense: a
        # review_by on it would be a promise about entries nobody may edit.
        # Same for the rotated quarterly archives it spills into.
        if path.resolve() in exempt or archive in path.resolve().parents:
            continue
        # Decision records carry their own front matter (id, status, date) and
        # are immutable once accepted, so a review_by on one would be a promise
        # nobody is allowed to keep. Whether the front matter itself is even
        # parseable is checked separately, by check_adr_immutability.
        # The archive adr_compact.py moves them into is the same kind of file.
        if path.resolve().parent == decisions or adr_archive in path.resolve().parents:
            continue
        yield path


def adr_files(repo: Path, archived: bool = False):
    """Decision record files, sorted by id. Live ones by default; archived=True
    reads the folder adr_compact.py moves the oldest into instead."""
    decisions = repo / (DECISIONS_ARCHIVE_DIR if archived else DECISIONS_DIR)
    if not decisions.is_dir():
        return []
    return sorted(p for p in decisions.glob("DEC-*.md") if p.is_file())


def load_adrs(repo: Path, archived: bool = False):
    """Every decision record as a dict, with superseded_by derived from the
    other records rather than stored -- that is what keeps accepted files
    immutable."""
    records = []
    for path in adr_files(repo, archived):
        front, _ = read_front_matter(path)
        # Fall back to the filename prefix (DEC-0007-slug -> DEC-0007) so a
        # record with broken front matter still appears in the index instead of
        # vanishing from it.
        fallback_id = "-".join(path.stem.split("-")[:2])
        records.append(
            {
                "path": path,
                "id": str(front.get("id") or fallback_id),
                "title": front.get("title", ""),
                "status": front.get("status", ""),
                "date": str(front.get("date", "")),
                "supersedes": front.get("supersedes") or [],
                "tags": front.get("tags") or [],
                "superseded_by": [],
            }
        )
    by_id = {r["id"]: r for r in records}
    for record in records:
        for old in record["supersedes"]:
            if old in by_id:
                by_id[old]["superseded_by"].append(record["id"])
    return records


def adr_status(record) -> str:
    """A decision record's status, lowercased, from a load_adrs record or a
    parsed front-matter dict. Status matches in any case, so "Accepted" is
    accepted, and str() comes first because YAML can hand back a bool, a date
    or a list. One definition, so the audit and compaction cannot drift into
    two answers for what a record's status is."""
    return str(record.get("status") or "").lower()


def git(repo: Path, *args):
    """Run a git command, returning stdout or None if git cannot answer."""
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
        )
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout


def is_git_repo(repo: Path) -> bool:
    return git(repo, "rev-parse", "--git-dir") is not None


def markdown_docs(repo: Path):
    """Every Markdown file that counts as documentation, skipping vendored and
    generated trees."""
    skip = {".git", "node_modules", "vendor", "dist", "build", ".venv"}
    for path in sorted(repo.rglob("*.md")):
        # Relative to the audited repo, never the absolute path: a repo checked
        # out under a directory called build/ or dist/ -- a CI workspace root,
        # commonly -- matched every one of its own documents against the skip
        # set and yielded nothing, which turned check_phi_secrets into a pass.
        if any(part in skip for part in path.relative_to(repo).parts):
            continue
        yield path


def strip_code(text: str) -> str:
    """Remove fenced blocks, inline code, and URLs. Prose checks run on what is
    left; flagging a term inside a code sample is noise."""
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    text = re.sub(r"`[^`\n]*`", "", text)
    # Stop at ")" as well as whitespace: a markdown link's closing paren
    # ("[text](https://url)") is not part of the URL, and \S alone swallows it.
    text = re.sub(r"https?://[^\s)]+", "", text)
    return text
