#!/usr/bin/env python3
"""Turn a repository's docs/GLOSSARY.md into the Vale vocabulary and swap rules.

Usage: glossary_to_vale.py <repo> [--styles-path styles]

Reads the four-column glossary table and writes:

  styles/config/vocabularies/Project/accept.txt   approved terms
  styles/config/vocabularies/Project/reject.txt   terms from "Do not use"
  styles/Clarity/GlossaryTerms.yml         reject -> approved substitutions

Approved and rejected terms come only from the repository's own glossary. The
skill ships an empty vocabulary on purpose: a word list bundled with the tool
would be someone else's vocabulary imposed on every repo.
"""
import argparse
import sys
from pathlib import Path

from _common import GLOSSARY

HEADER = (
    f"# Generated by glossary_to_vale.py from {GLOSSARY} - do not edit.\n"
    f"# Add or change terms in {GLOSSARY} and re-run the script.\n"
)


def parse_glossary(path: Path):
    """Return [(term, [rejected, ...])] from the glossary table."""
    entries = []
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            continue
        term, rejected = cells[0], cells[2]
        if not term or term.lower() == "term" or set(term) <= {"-", ":", " "}:
            continue
        if term.startswith("{{"):  # untouched template row
            continue
        rejects = [r.strip() for r in rejected.split(",")
                   if r.strip() and not r.strip().startswith("{{")]
        entries.append((term, rejects))
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(
        description=f"Build the Vale vocabulary from {GLOSSARY}")
    parser.add_argument("repo", type=Path)
    parser.add_argument("--styles-path", default="styles",
                        help="styles directory, relative to the repo (default: styles)")
    args = parser.parse_args()

    repo = args.repo.resolve()
    glossary = repo / GLOSSARY
    if not glossary.is_file():
        print(f"error: no {GLOSSARY} in {repo}", file=sys.stderr)
        return 1

    entries = parse_glossary(glossary)
    if not entries:
        print(f"error: {GLOSSARY} has no term rows", file=sys.stderr)
        return 1

    styles = repo / args.styles_path
    vocab = styles / "config" / "vocabularies" / "Project"
    vocab.mkdir(parents=True, exist_ok=True)
    (styles / "Clarity").mkdir(parents=True, exist_ok=True)

    accept = sorted(term for term, _ in entries)
    reject = sorted({r for _, rejects in entries for r in rejects})
    (vocab / "accept.txt").write_text("\n".join(accept) + "\n", encoding="utf-8")
    (vocab / "reject.txt").write_text("\n".join(reject) + "\n", encoding="utf-8")

    swap = {r: term for term, rejects in entries for r in rejects}
    lines = [
        HEADER,
        "extends: substitution",
        f'message: "Use \'%s\' instead of \'%s\' ({GLOSSARY})."',
        "level: error",
        "ignorecase: true",
        "swap:",
    ]
    if swap:
        lines += [f'  "{bad}": "{good}"' for bad, good in sorted(swap.items())]
    else:
        lines.append("  {}")
    (styles / "Clarity" / "GlossaryTerms.yml").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(accept)} approved term(s), {len(reject)} rejected term(s)")
    print(f"wrote {(vocab / 'accept.txt').relative_to(repo)}, "
          f"{(vocab / 'reject.txt').relative_to(repo)}, "
          f"{(styles / 'Clarity' / 'GlossaryTerms.yml').relative_to(repo)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
