#!/usr/bin/env python3
"""Render docs/architecture/domain-model.md for a repository.

Usage: domain_model.py <repo> [--write] [--check]

Default prints the document. --write commits it to disk. --check exits 1 when
what is committed differs from what would be generated, and 2 when the
extractor found no source file it can read -- the audit turns that 2 into
`skipped`, because a C or Rust repository has not failed anything.

Same contract as adr_index.py --check, deliberately: one way to ask a
docs-warden generator whether the tree is current.
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
# _common lives with the docs-warden skill's scripts. Resolved from __file__ so
# it works from any working directory, and from the installed plugin cache.
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "docs-warden" / "scripts"))

from extract_concepts import LANGUAGES, extract  # noqa: E402
from _common import (  # noqa: E402
    DECISIONS_DIR,
    DOMAIN_MODEL,
    GENERATED_MARKER,
    RUNLOG,
    RUNLOG_ARCHIVE_DIR,
    load_config,
    read_front_matter,
)

# Past this many nodes a Mermaid graph is a hairball nobody reads, and it is
# honest to say so rather than to render it.
MAX_GRAPH_NODES = 60

ARROWS = {
    "is_a": "-->|is a|",
    "part_of": "-->|part of|",
    "depends_on": "-.->",
    "associates_with": "---",
}

PREAMBLE = (
    "Generated by `domain_model.py` from {count} source file{plural} ({languages}). "
    "Categories come\nfrom a naming heuristic (`references/concept-categories.md`); "
    "a concept in the wrong table is\nfixed by renaming it in code or listing it under "
    "`ontology.overrides:` in `.docs-warden.yml`,\nnever by editing this file."
)


def documentation_docs(repo: Path):
    """Documents under docs/ that may carry a `concepts:` tag: the long-lived
    ones. Generated files, the run log and decision records are excluded for
    the same reasons check_front_matter excludes them."""
    docs = repo / "docs"
    if not docs.is_dir():
        return
    exempt = {(repo / RUNLOG).resolve()}
    archive = (repo / RUNLOG_ARCHIVE_DIR).resolve()
    decisions = (repo / DECISIONS_DIR).resolve()
    for path in sorted(docs.rglob("*.md")):
        resolved = path.resolve()
        if resolved in exempt or archive in resolved.parents:
            continue
        if decisions in resolved.parents:
            continue
        try:
            if path.read_text(encoding="utf-8", errors="replace").startswith(
                    GENERATED_MARKER):
                continue
        except OSError:
            continue
        yield path


def documented_in(repo: Path):
    """{concept: [doc path, ...]} from every `concepts:` front-matter list."""
    tags = {}
    for path in documentation_docs(repo):
        front, _ = read_front_matter(path)
        names = front.get("concepts")
        if not isinstance(names, list):
            continue
        rel = path.relative_to(repo).as_posix()
        for name in names:
            tags.setdefault(str(name), []).append(rel)
    return {name: sorted(set(paths)) for name, paths in tags.items()}


def ontology_settings(config):
    section = (config or {}).get("ontology") or {}
    if not isinstance(section, dict):
        return {}, None
    overrides = section.get("overrides") or {}
    if not isinstance(overrides, dict):
        overrides = {}
    paths = section.get("source_paths")
    if not isinstance(paths, list) or not all(isinstance(p, str) for p in paths):
        paths = None
    return {str(k): str(v) for k, v in overrides.items()}, paths


def apply_overrides(concepts, overrides):
    """A human's correction of the naming heuristic, applied after extraction.
    Unknown values are ignored here and reported by the audit's manifest check:
    one place says what a bad manifest means."""
    result = {}
    for name, data in concepts.items():
        verdict = overrides.get(name)
        if verdict == "ignore":
            continue
        if verdict in ("domain", "technical"):
            data = dict(data, category=verdict)
        result[name] = data
    return result


def _cell(value: str) -> str:
    return (value or "").replace("|", r"\|").replace("\n", " ").strip()


def _node(name: str) -> str:
    node_id = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return node_id if node_id == name else f'{node_id}["{name}"]'


def render_graph(model, concepts):
    edges = []
    nodes = set()
    for relationship, arrow in ARROWS.items():
        for edge in model["relationships"].get(relationship, []):
            subject, obj = edge["subject"], edge["object"]
            if subject not in concepts or obj not in concepts:
                continue
            nodes.update((subject, obj))
            edges.append(f"    {_node(subject)} {arrow} {_node(obj)}")
    if not edges:
        return ["No relationships were extracted from this tree."]
    if len(nodes) > MAX_GRAPH_NODES:
        return [f"{len(nodes)} concepts are related here, past the "
                f"{MAX_GRAPH_NODES}-node limit a readable diagram has. "
                f"The tables above carry the same information."]
    return ["```mermaid", "graph TD", *sorted(edges), "```"]


def render(model, tags):
    concepts = model["concepts"]
    count = sum(model["sources"].values())
    languages = ", ".join(lang for lang in LANGUAGES if model["sources"].get(lang))
    lines = [
        GENERATED_MARKER,
        "",
        "# Domain model",
        "",
        PREAMBLE.format(count=count, plural="" if count == 1 else "s",
                        languages=languages or "none"),
        "",
        "## Domain concepts",
        "",
        "| Concept | Kind | Defined in | Summary | Documented in |",
        "|---------|------|------------|---------|---------------|",
    ]
    for name, data in sorted(concepts.items()):
        if data["category"] != "domain":
            continue
        where = ", ".join(f"`{p}`" for p in tags.get(name, []))
        lines.append(f"| {_cell(name)} | {_cell(data['kind'])} | "
                     f"`{_cell(data['defined_in'])}` | {_cell(data['summary'])} | "
                     f"{where} |")
    lines += ["", "## Technical concepts", "",
              "| Concept | Kind | Defined in |",
              "|---------|------|------------|"]
    for name, data in sorted(concepts.items()):
        if data["category"] != "technical":
            continue
        lines.append(f"| {_cell(name)} | {_cell(data['kind'])} | "
                     f"`{_cell(data['defined_in'])}` |")
    lines += ["", "## Relationships", ""] + render_graph(model, concepts) + [""]
    return "\n".join(lines)


def build(repo: Path):
    """(document text, source file count) for a repository."""
    overrides, source_paths = ontology_settings(load_config(repo))
    model = extract(repo, source_paths)
    model["concepts"] = apply_overrides(model["concepts"], overrides)
    return render(model, documented_in(repo)), sum(model["sources"].values())


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo")
    parser.add_argument("--write", action="store_true",
                        help=f"write {DOMAIN_MODEL}")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed document is stale, 2 if "
                             "there is nothing this extractor can read")
    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve()
    text, sources = build(repo)
    target = repo / DOMAIN_MODEL

    if args.check:
        if not sources:
            print(f"no supported source files under {args.repo}; "
                  f"the extractor reads Python, JS/TS, PowerShell and Terraform",
                  file=sys.stderr)
            return 2
        if not target.is_file():
            print(f"{DOMAIN_MODEL} is missing", file=sys.stderr)
            return 1
        if target.read_text(encoding="utf-8", errors="replace") != text:
            print(f"{DOMAIN_MODEL} differs from what domain_model.py generates",
                  file=sys.stderr)
            return 1
        return 0

    if args.write:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")
        print(f"wrote {DOMAIN_MODEL}")
        return 0

    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
